estimator: random_forest # Options: random_forest, svm, knn
normalize: True # Options: True, False
seed: 42
save_train_data: True 
dataset: digits
automatic_commit:
  activated: True
  working_dir: /csem/divr/users/tbe/repo/experiment_tracker